@tool
class_name Character
extends Resource

## Auto-generated Resource class for Character data type
## Generated by Data Systems Plugin

@export var powers: Array = []

func _init() -> void:
	pass

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"powers": powers
	}

## Load from dictionary
func from_dict(data: Dictionary) -> void:
	if data.has("powers"):
		powers = data["powers"]
