@tool
class_name DataItem
extends Resource

## Base class for all data instances managed by the database system.
## Each table type has a generated subclass (e.g. Level, Item, Enemy).
## Subclasses are generated by ResourceGenerator.

## Human-readable name set by the designer. Becomes the enum key in generated IDs file.
@export var name: String = ""

## Stable auto-incremented ID. Assigned by DatabaseManager, never reused.
## This is the enum value — do not edit manually.
var id: int = -1
