@tool
class_name DataItem
extends Resource

## Base class for all data instances managed by the database system.
## Each table type has a generated subclass (e.g. Level, Item, Enemy).
## Subclasses are generated by ResourceGenerator.
