@tool
class_name Level
extends DataItem

## Auto-generated DataItem subclass for Level table
## Generated by Data Systems Plugin — do not edit manually

@export var unlock_conditions: Array = []
@export var background_color: Color = Color("000000ff")
@export var aaaa: String = ""
