@tool
class_name ResourceGenerator
extends RefCounted

## Generates GDScript Resource classes (table structures)
## Creates .gd files that serve as both schema definitions and typed DataItem subclasses

const BASE_RESOURCES_PATH = "res://data/res/table_structures/"

## Property types supported by the system
enum PropertyType {
	INT, FLOAT, STRING, BOOL, TEXTURE2D,
	VECTOR2, VECTOR3, COLOR, ARRAY, DICTIONARY
}

const TYPE_DEFAULTS = {
	PropertyType.INT: 0,
	PropertyType.FLOAT: 0.0,
	PropertyType.STRING: "",
	PropertyType.BOOL: false,
	PropertyType.TEXTURE2D: null,
	PropertyType.VECTOR2: Vector2.ZERO,
	PropertyType.VECTOR3: Vector3.ZERO,
	PropertyType.COLOR: Color.WHITE,
	PropertyType.ARRAY: [],
	PropertyType.DICTIONARY: {}
}


## Generate Resource class file from type name and properties
## properties: Array of {name: String, type: PropertyType, default: Variant}
static func generate_resource_class(type_name: String, properties: Array[Dictionary]) -> Error:
	var file_path = _get_resource_file_path(type_name)
	var script_content = _generate_script_content(type_name, properties)

	var error = _ensure_directory(BASE_RESOURCES_PATH)
	if error != OK:
		push_error("Failed to create resources directory")
		return error

	var file = FileAccess.open(file_path, FileAccess.WRITE)
	if file == null:
		error = FileAccess.get_open_error()
		push_error("Failed to create resource file: %s (Error: %d)" % [file_path, error])
		return error

	file.store_string(script_content)
	file.close()

	print("[ResourceGenerator] Generated: %s" % file_path)
	return OK


## Generate script content
static func _generate_script_content(type_name: String, properties: Array[Dictionary]) -> String:
	var lines: Array[String] = []

	lines.append("@tool")
	lines.append("class_name %s" % type_name)
	lines.append("extends DataItem")
	lines.append("")
	lines.append("## Auto-generated DataItem subclass for %s data type" % type_name)
	lines.append("## Generated by Data Systems Plugin")
	lines.append("")

	for prop in properties:
		var type_str = _get_gdscript_type(prop.type)
		var default_str = _get_default_value_string(prop.default, prop.type)
		lines.append("@export var %s: %s = %s" % [prop.name, type_str, default_str])

	lines.append("")
	lines.append("func _init() -> void:")
	lines.append("\tpass")
	lines.append("")

	lines.append("func get_type_name() -> String:")
	lines.append("\treturn \"%s\"" % type_name)
	lines.append("")

	lines.append("func to_dict() -> Dictionary:")
	lines.append("\treturn {")
	for i in range(properties.size()):
		var prop = properties[i]
		var comma = "," if i < properties.size() - 1 else ""
		lines.append("\t\t\"%s\": %s%s" % [prop.name, prop.name, comma])
	lines.append("\t}")
	lines.append("")

	lines.append("func from_dict(data: Dictionary) -> void:")
	for prop in properties:
		lines.append("\tif data.has(\"%s\"):" % prop.name)
		lines.append("\t\t%s = data[\"%s\"]" % [prop.name, prop.name])
	lines.append("")

	return "\n".join(lines)


## Convert Variant.Type (from script reflection) back to PropertyType
## prop_info: Dictionary from get_script_property_list()
static func variant_type_to_property_type(prop_info: Dictionary) -> PropertyType:
	match prop_info.type:
		TYPE_INT:
			return PropertyType.INT
		TYPE_FLOAT:
			return PropertyType.FLOAT
		TYPE_STRING:
			return PropertyType.STRING
		TYPE_BOOL:
			return PropertyType.BOOL
		TYPE_OBJECT:
			var cls = prop_info.get("class_name", "")
			if cls == &"Texture2D" or prop_info.get("hint_string", "") == "Texture2D":
				return PropertyType.TEXTURE2D
			return PropertyType.TEXTURE2D
		TYPE_VECTOR2:
			return PropertyType.VECTOR2
		TYPE_VECTOR3:
			return PropertyType.VECTOR3
		TYPE_COLOR:
			return PropertyType.COLOR
		TYPE_ARRAY:
			return PropertyType.ARRAY
		TYPE_DICTIONARY:
			return PropertyType.DICTIONARY
		_:
			return PropertyType.STRING


## Regenerate all resource classes
static func regenerate_all(type_data: Array[Dictionary]) -> int:
	var count = 0
	for entry in type_data:
		if generate_resource_class(entry.type_name, entry.properties) == OK:
			count += 1
	print("[ResourceGenerator] Regenerated %d resource classes" % count)
	return count


## Get GDScript type string
static func _get_gdscript_type(prop_type: PropertyType) -> String:
	match prop_type:
		PropertyType.INT: return "int"
		PropertyType.FLOAT: return "float"
		PropertyType.STRING: return "String"
		PropertyType.BOOL: return "bool"
		PropertyType.TEXTURE2D: return "Texture2D"
		PropertyType.VECTOR2: return "Vector2"
		PropertyType.VECTOR3: return "Vector3"
		PropertyType.COLOR: return "Color"
		PropertyType.ARRAY: return "Array"
		PropertyType.DICTIONARY: return "Dictionary"
		_: return "Variant"


## Get default value as GDScript string
static func _get_default_value_string(value: Variant, prop_type: PropertyType) -> String:
	match prop_type:
		PropertyType.INT:
			return str(value if value != null else 0)
		PropertyType.FLOAT:
			return str(value if value != null else 0.0)
		PropertyType.STRING:
			return '"%s"' % (value if value != null else "")
		PropertyType.BOOL:
			return "true" if value else "false"
		PropertyType.TEXTURE2D:
			if value is Texture2D and !value.resource_path.is_empty():
				return 'preload("%s")' % value.resource_path
			return "null"
		PropertyType.VECTOR2:
			if value is Vector2:
				return "Vector2(%f, %f)" % [value.x, value.y]
			return "Vector2.ZERO"
		PropertyType.VECTOR3:
			if value is Vector3:
				return "Vector3(%f, %f, %f)" % [value.x, value.y, value.z]
			return "Vector3.ZERO"
		PropertyType.COLOR:
			if value is Color:
				return 'Color("%s")' % value.to_html()
			return "Color.WHITE"
		PropertyType.ARRAY:
			return "[]"
		PropertyType.DICTIONARY:
			return "{}"
		_:
			return "null"


## Get resource file path for a type
static func _get_resource_file_path(type_name: String) -> String:
	return BASE_RESOURCES_PATH.path_join(type_name.to_lower() + ".gd")


## Check if resource class exists
static func resource_exists(type_name: String) -> bool:
	return FileAccess.file_exists(_get_resource_file_path(type_name))


## Delete resource class file
static func delete_resource_class(type_name: String) -> Error:
	var file_path = _get_resource_file_path(type_name)
	if !FileAccess.file_exists(file_path):
		return ERR_FILE_NOT_FOUND
	var dir = DirAccess.open(BASE_RESOURCES_PATH)
	if dir == null:
		return DirAccess.get_open_error()
	return dir.remove(file_path.get_file())


## Ensure directory exists
static func _ensure_directory(dir_path: String) -> Error:
	if DirAccess.dir_exists_absolute(dir_path):
		return OK
	return DirAccess.make_dir_recursive_absolute(dir_path)
