@tool
class_name ResourceGenerator
extends RefCounted

## Generates GDScript Resource classes (table structures) and enum ID files.
## Creates .gd files that serve as both schema definitions and typed DataItem subclasses.

const DEFAULT_STRUCTURES_PATH = "res://database/res/table_structures/"
const DEFAULT_IDS_PATH = "res://database/res/ids/"

## Property types supported by the system
enum PropertyType {
	INT, FLOAT, STRING, BOOL, TEXTURE2D,
	VECTOR2, VECTOR3, COLOR, ARRAY, DICTIONARY
}

const TYPE_DEFAULTS = {
	PropertyType.INT: 0,
	PropertyType.FLOAT: 0.0,
	PropertyType.STRING: "",
	PropertyType.BOOL: false,
	PropertyType.TEXTURE2D: null,
	PropertyType.VECTOR2: Vector2.ZERO,
	PropertyType.VECTOR3: Vector3.ZERO,
	PropertyType.COLOR: Color.WHITE,
	PropertyType.ARRAY: [],
	PropertyType.DICTIONARY: {}
}


# --- Resource Class Generation -----------------------------------------------

## Generate Resource class file from table name and properties
## properties: Array of {name: String, type: PropertyType, default: Variant}
static func generate_resource_class(table_name: String, properties: Array[Dictionary], base_path: String = DEFAULT_STRUCTURES_PATH) -> Error:
	var file_path = base_path.path_join(table_name.to_lower() + ".gd")
	var script_content = _generate_script_content(table_name, properties)

	var error = _ensure_directory(base_path)
	if error != OK:
		push_error("Failed to create resources directory")
		return error

	var file = FileAccess.open(file_path, FileAccess.WRITE)
	if file == null:
		error = FileAccess.get_open_error()
		push_error("Failed to create resource file: %s (Error: %d)" % [file_path, error])
		return error

	file.store_string(script_content)
	file.close()

	print("[ResourceGenerator] Generated: %s" % file_path)
	return OK


## Delete resource class file
static func delete_resource_class(table_name: String, base_path: String = DEFAULT_STRUCTURES_PATH) -> Error:
	var file_path = base_path.path_join(table_name.to_lower() + ".gd")
	if !FileAccess.file_exists(file_path):
		return ERR_FILE_NOT_FOUND
	var dir = DirAccess.open(base_path)
	if dir == null:
		return DirAccess.get_open_error()
	return dir.remove(file_path.get_file())


## Check if resource class exists
static func resource_exists(table_name: String, base_path: String = DEFAULT_STRUCTURES_PATH) -> bool:
	return FileAccess.file_exists(base_path.path_join(table_name.to_lower() + ".gd"))


## Regenerate all resource classes
static func regenerate_all(table_data: Array[Dictionary], base_path: String = DEFAULT_STRUCTURES_PATH) -> int:
	var count = 0
	for entry in table_data:
		if generate_resource_class(entry.table_name, entry.properties, base_path) == OK:
			count += 1
	print("[ResourceGenerator] Regenerated %d resource classes" % count)
	return count


# --- Enum ID File Generation -------------------------------------------------

## Generate an enum .gd file for a table's instances.
## Only includes instances that have a non-empty `name` property.
static func generate_enum_file(table_name: String, instances: Array[DataItem], base_path: String = DEFAULT_IDS_PATH) -> Error:
	var error = _ensure_directory(base_path)
	if error != OK:
		push_error("Failed to create ids directory")
		return error

	var file_path = base_path.path_join(table_name.to_lower() + "_ids.gd")
	var content = _generate_enum_content(table_name, instances)

	var file = FileAccess.open(file_path, FileAccess.WRITE)
	if file == null:
		error = FileAccess.get_open_error()
		push_error("Failed to create enum file: %s (Error: %d)" % [file_path, error])
		return error

	file.store_string(content)
	file.close()

	print("[ResourceGenerator] Generated enum: %s" % file_path)
	return OK


## Delete enum file for a table
static func delete_enum_file(table_name: String, base_path: String = DEFAULT_IDS_PATH) -> Error:
	var file_path = base_path.path_join(table_name.to_lower() + "_ids.gd")
	if !FileAccess.file_exists(file_path):
		return ERR_FILE_NOT_FOUND
	var dir = DirAccess.open(base_path)
	if dir == null:
		return DirAccess.get_open_error()
	return dir.remove(file_path.get_file())


static func _generate_enum_content(table_name: String, instances: Array[DataItem]) -> String:
	var class_name_str = "%sIds" % table_name
	var lines: Array[String] = []

	lines.append("class_name %s" % class_name_str)
	lines.append("")
	lines.append("## Auto-generated by DatabaseManager — do not edit manually")
	lines.append("")
	lines.append("enum Id {")

	var entries: Array[String] = []
	for item in instances:
		if item.name.is_empty():
			continue
		var key = _sanitize_enum_key(item.name)
		if key.is_empty():
			continue
		entries.append("\t%s = %d," % [key, item.id])

	for entry in entries:
		lines.append(entry)

	lines.append("}")
	lines.append("")
	return "\n".join(lines)


## Convert a human-readable name to a valid GDScript enum key
## "Forest Level" → "FOREST_LEVEL", "my-item" → "MY_ITEM"
static func _sanitize_enum_key(name_str: String) -> String:
	var result = name_str.strip_edges().to_upper()
	# Replace spaces, hyphens, dots with underscores
	result = result.replace(" ", "_")
	result = result.replace("-", "_")
	result = result.replace(".", "_")
	# Remove any character that's not alphanumeric or underscore
	var sanitized := ""
	for i in range(result.length()):
		var c = result[i]
		if c == "_" or (c >= "A" and c <= "Z") or (c >= "0" and c <= "9"):
			sanitized += c
	# Ensure it doesn't start with a digit
	if sanitized.length() > 0 and sanitized[0] >= "0" and sanitized[0] <= "9":
		sanitized = "_" + sanitized
	# Collapse multiple underscores
	while sanitized.contains("__"):
		sanitized = sanitized.replace("__", "_")
	return sanitized


# --- Script Content Generation -----------------------------------------------

static func _generate_script_content(table_name: String, properties: Array[Dictionary]) -> String:
	var lines: Array[String] = []

	lines.append("@tool")
	lines.append("class_name %s" % table_name)
	lines.append("extends DataItem")
	lines.append("")
	lines.append("## Auto-generated DataItem subclass for %s table" % table_name)
	lines.append("## Generated by Data Systems Plugin — do not edit manually")
	lines.append("")

	for prop in properties:
		var type_str = _get_gdscript_type(prop.type)
		var default_str = _get_default_value_string(prop.default, prop.type)
		lines.append("@export var %s: %s = %s" % [prop.name, type_str, default_str])

	lines.append("")
	return "\n".join(lines)


## Convert Variant.Type (from script reflection) back to PropertyType
## prop_info: Dictionary from get_script_property_list()
static func variant_type_to_property_type(prop_info: Dictionary) -> PropertyType:
	match prop_info.type:
		TYPE_INT:
			return PropertyType.INT
		TYPE_FLOAT:
			return PropertyType.FLOAT
		TYPE_STRING:
			return PropertyType.STRING
		TYPE_BOOL:
			return PropertyType.BOOL
		TYPE_OBJECT:
			var cls = prop_info.get("class_name", "")
			if cls == &"Texture2D" or prop_info.get("hint_string", "") == "Texture2D":
				return PropertyType.TEXTURE2D
			return PropertyType.TEXTURE2D
		TYPE_VECTOR2:
			return PropertyType.VECTOR2
		TYPE_VECTOR3:
			return PropertyType.VECTOR3
		TYPE_COLOR:
			return PropertyType.COLOR
		TYPE_ARRAY:
			return PropertyType.ARRAY
		TYPE_DICTIONARY:
			return PropertyType.DICTIONARY
		_:
			return PropertyType.STRING


# --- Helpers -----------------------------------------------------------------

static func _get_gdscript_type(prop_type: PropertyType) -> String:
	match prop_type:
		PropertyType.INT: return "int"
		PropertyType.FLOAT: return "float"
		PropertyType.STRING: return "String"
		PropertyType.BOOL: return "bool"
		PropertyType.TEXTURE2D: return "Texture2D"
		PropertyType.VECTOR2: return "Vector2"
		PropertyType.VECTOR3: return "Vector3"
		PropertyType.COLOR: return "Color"
		PropertyType.ARRAY: return "Array"
		PropertyType.DICTIONARY: return "Dictionary"
		_: return "Variant"


static func _get_default_value_string(value: Variant, prop_type: PropertyType) -> String:
	match prop_type:
		PropertyType.INT:
			return str(value if value != null else 0)
		PropertyType.FLOAT:
			return str(value if value != null else 0.0)
		PropertyType.STRING:
			return '"%s"' % (value if value != null else "")
		PropertyType.BOOL:
			return "true" if value else "false"
		PropertyType.TEXTURE2D:
			if value is Texture2D and !value.resource_path.is_empty():
				return 'preload("%s")' % value.resource_path
			return "null"
		PropertyType.VECTOR2:
			if value is Vector2:
				return "Vector2(%f, %f)" % [value.x, value.y]
			return "Vector2.ZERO"
		PropertyType.VECTOR3:
			if value is Vector3:
				return "Vector3(%f, %f, %f)" % [value.x, value.y, value.z]
			return "Vector3.ZERO"
		PropertyType.COLOR:
			if value is Color:
				return 'Color("%s")' % value.to_html()
			return "Color.WHITE"
		PropertyType.ARRAY:
			return "[]"
		PropertyType.DICTIONARY:
			return "{}"
		_:
			return "null"


## Ensure directory exists, creating it recursively if needed.
static func _ensure_directory(dir_path: String) -> Error:
	if DirAccess.dir_exists_absolute(dir_path):
		return OK
	return DirAccess.make_dir_recursive_absolute(dir_path)
