@tool
class_name Level
extends DataItem

## Auto-generated DataItem subclass for Level data type
## Generated by Data Systems Plugin

@export var reward: int = 0.0
@export var unlock_conditions: Array = []

func _init() -> void:
	pass

## Returns the schema name for this data type
func get_type_name() -> String:
	return "Level"

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"reward": reward,
		"unlock_conditions": unlock_conditions
	}

## Load from dictionary
func from_dict(data: Dictionary) -> void:
	if data.has("reward"):
		reward = data["reward"]
	if data.has("unlock_conditions"):
		unlock_conditions = data["unlock_conditions"]
