@tool
class_name Levels
extends DataItem

## Auto-generated DataItem subclass for Levels data type
## Generated by Data Systems Plugin

@export var icon: String = ""

func _init() -> void:
	pass

## Returns the schema name for this data type
func get_type_name() -> String:
	return "Levels"

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"icon": icon
	}

## Load from dictionary
func from_dict(data: Dictionary) -> void:
	if data.has("icon"):
		icon = data["icon"]
