@tool
class_name sdfsdf
extends DataItem

## Auto-generated DataItem subclass for sdfsdf data type
## Generated by Data Systems Plugin

@export var a: String = ""

func _init() -> void:
	pass

## Returns the schema name for this data type
func get_type_name() -> String:
	return "sdfsdf"

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"a": a
	}

## Load from dictionary
func from_dict(data: Dictionary) -> void:
	if data.has("a"):
		a = data["a"]
