@tool
class_name sss
extends DataItem

## Auto-generated DataItem subclass for sss data type
## Generated by Data Systems Plugin

@export var aaa: String = ""

func _init() -> void:
	pass

## Returns the schema name for this data type
func get_type_name() -> String:
	return "sss"

## Convert to dictionary for serialization
func to_dict() -> Dictionary:
	return {
		"aaa": aaa
	}

## Load from dictionary
func from_dict(data: Dictionary) -> void:
	if data.has("aaa"):
		aaa = data["aaa"]
