@tool
class_name aaa
extends DataItem

## Auto-generated DataItem subclass for aaa table
## Generated by Data Systems Plugin — do not edit manually

@export var w: String = ""
@export var q: String = ""
@export var new: String = ""
@export var new2: String = ""
@export var new3: String = ""
