@tool
class_name AchievementData
extends DataItem

## Auto-generated DataItem subclass for AchievementData table
## Generated by Data Systems Plugin — do not edit manually

@export var reward: int = 0.0
@export var icon: Texture2D = null
