@tool
class_name AllyLevelData
extends DataItem

## Auto-generated DataItem subclass for AllyLevelData table
## Generated by Data Systems Plugin — do not edit manually

func _init():
	_required_fields = ["price"]
	_fk_fields = {"ally": "AllyData"}

@export var price: int = 0
@export var ally: AllyData = null
