@tool
class_name AllyData
extends DataItem

## Auto-generated DataItem subclass for AllyData table
## Generated by Data Systems Plugin — do not edit manually

@export var description: String = ""
@export var shield_color: Color = Color.AQUA
