@tool
class_name ExplosivesLevelData
extends "res://database/res/table_structures/allyleveldata.gd"

## Auto-generated DataItem subclass for ExplosivesLevelData table
## Generated by Data Systems Plugin — do not edit manually

@export var range: int = 0
