@tool
class_name ExplosivesLevelData
extends AllyLevelData

## Auto-generated DataItem subclass for ExplosivesLevelData table
## Generated by Data Systems Plugin — do not edit manually

@export var range: int = 0
