@tool
class_name LevelDat
extends DataItem

## Auto-generated DataItem subclass for LevelDat table
## Generated by Data Systems Plugin — do not edit manually

@export var unlocked_conditions: Array[int] = []
