@tool
class_name LevelUserData
extends DataItem

## Auto-generated DataItem subclass for LevelUserData table
## Generated by Data Systems Plugin — do not edit manually

@export var completed: int = 0.0
