@tool
class_name NewLevelData
extends DataItem

## Auto-generated DataItem subclass for NewLevelData table
## Generated by Data Systems Plugin — do not edit manually

@export var test1: String = ""
@export var test2: String = ""
@export var tes3: String = ""
@export var test4: String = ""
@export var test5: String = ""
