@tool
class_name ResourceProviderLevelData
extends AllyLevelData

## Auto-generated DataItem subclass for ResourceProviderLevelData table
## Generated by Data Systems Plugin — do not edit manually

func _init():
	_required_fields = ["providing_interval_seconds"]

@export var providing_interval_seconds: float = 0.0
