@tool
class_name ShooterAllyLevelData
extends "res://database/res/table_structures/allyleveldata.gd"

## Auto-generated DataItem subclass for ShooterAllyLevelData table
## Generated by Data Systems Plugin — do not edit manually

func _init():
	_required_fields = ["shooting_wait_interval_sec"]

@export var shooting_wait_interval_sec: int = 0
