@tool
class_name UserLevelData
extends DataItem

## Auto-generated DataItem subclass for UserLevelData table
## Generated by Data Systems Plugin — do not edit manually

@export var completed: String = ""
