@tool
class_name Achievement
extends DataItem

## Auto-generated DataItem subclass for Achievement data type
## Generated by Data Systems Plugin

@export var icon: String = ""

func _init() -> void:
	pass

func get_type_name() -> String:
	return "Achievement"

func to_dict() -> Dictionary:
	return {
		"icon": icon
	}

func from_dict(data: Dictionary) -> void:
	if data.has("icon"):
		icon = data["icon"]
