@tool
class_name Level
extends DataItem

## Auto-generated DataItem subclass for Level data type
## Generated by Data Systems Plugin

@export var unlocked_conditions: String = ""

func _init() -> void:
	pass

func get_type_name() -> String:
	return "Level"

func to_dict() -> Dictionary:
	return {
		"unlocked_conditions": unlocked_conditions
	}

func from_dict(data: Dictionary) -> void:
	if data.has("unlocked_conditions"):
		unlocked_conditions = data["unlocked_conditions"]
